"""initial migration

Revision ID: 23d3ec705564
Revises: 44b895af6794
Create Date: 2023-11-20 14:56:03.541797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d3ec705564'
down_revision = '44b895af6794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        # Додавання нової колонки 'complete'
        batch_op.add_column(sa.Column('complete', sa.Boolean(), nullable=True))

        # Зміна налаштувань існуючої колонки 'title'
        batch_op.alter_column('title',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=True)

        # Перевірка наявності колонки 'description' перед видаленням
        table = batch_op.get_table('todo')
        if 'description' in table.columns:
            batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('complete')

    # ### end Alembic commands ###
